_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 6b6d0ad6-2169-43d9-bd03-7dc36eb58575
name: 'Drupal LMS Demo'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /courses
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
